name: signwriter_easy_app_oficial
description: "Aplicativo para facilitar a comunicação entre surdos e ouvintes."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  supabase_flutter: 2.12.0
  gotrue: 2.18.0
  fl_chart: ^0.70.0
  flutter_dotenv: ^5.1.0
  share_plus: ^7.2.0
  path_provider: ^2.1.0
  image_picker: ^1.1.2
  speech_to_text: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/learning/
    - assets/signs/
    - assets/signs_catalog.json
    - .env

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/signwriter_logo.png"
  remove_alpha_ios: true
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/signwriter_logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/signwriter_logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/signwriter_logo.png"